# Note that this environment file is overspecified to reflect the exact environment in which experiments were originally run.
# If you have any installation problems, you will likely want to change/remove version numbers, or add/remove dependencies as necessary.
name: mufasa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Comment the below files back in for Windows 10.
  #- m2w64-gcc-libgfortran=5.3.0
  #- m2w64-gcc-libs=5.3.0
  #- m2w64-gcc-libs-core=5.3.0
  #- m2w64-gmp=6.1.0
  #- m2w64-libwinpthread-git=5.0.0.4634.697f757
  #- msys2-conda-epoch=20160418
  #- vc=14.2
  #- vs2015_runtime=14.28.29325
  #- win_inet_pton=1.1.0
  #- wincertstore=0.2
  # ^ End Windows
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cffi=1.14.2
  - chardet=3.0.4
  - cryptography=3.1
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - eagerpy=0.29.0
  - foolbox=3.1.1
  - freetype=2.10.2
  - git=2.28.0
  - gitdb=4.0.5
  - gitpython=3.1.8
  - icu=58.2
  - idna=2.10
  - intel-openmp=2020.2
  - jpeg=9b
  - kiwisolver=1.2.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.40.0
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ninja=1.10.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=7.2.0
  - pip=20.2.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.8.1
  - qt=5.9.7
  - requests=2.24.0
  - scipy=1.5.2
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - smmap=3.0.4
  - sqlite=3.33.0
  - tk=8.6.10
  - torchvision=0.9.1
  - tornado=6.0.4
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.25.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - configargparse==1.4
